export const PART_OF_SPEECH_OPTIONS = [
  { label: 'Noun', value: 'noun' },
  { label: 'Proper noun', value: 'proper noun' },
  { label: 'Pronoun', value: 'pronoun' },
  { label: 'Verb', value: 'verb' },
  { label: 'Auxiliary verb', value: 'auxiliary verb' },
  { label: 'Modal verb', value: 'modal verb' },
  { label: 'Phrasal verb', value: 'phrasal verb' },
  { label: 'Adjective', value: 'adjective' },
  { label: 'Adverb', value: 'adverb' },
  { label: 'Preposition', value: 'preposition' },
  { label: 'Conjunction', value: 'conjunction' },
  { label: 'Determiner', value: 'determiner' },
  { label: 'Article', value: 'article' },
  { label: 'Numeral', value: 'numeral' },
  { label: 'Interjection', value: 'interjection' },
  { label: 'Phrase', value: 'phrase' },
  { label: 'Idiom', value: 'idiom' },
] as const;
