export const API_ERROR_CODE = {
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_SLUG_ALREADY_EXISTS: 'CATEGORY_SLUG_ALREADY_EXISTS',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  INVALID_CATEGORY: 'INVALID_CATEGORY',
  INVALID_REQUEST: 'INVALID_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  WORD_NOT_FOUND: 'WORD_NOT_FOUND',
  WORD_SENSE_ALREADY_EXISTS: 'WORD_SENSE_ALREADY_EXISTS',
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODE)[keyof typeof API_ERROR_CODE];
